/**
 * A time-based one-time password (TOTP) is a temporary passcode, generated by an algorithm, 
 * for use in authenticating access to computer systems.
 * totp.generate(...)
 * totp.check(...)
 * totp.verify(...)
 */
const totp = require('otplib/totp')
const crypto = require('crypto')

totp.options = {
	crypto
};

const TOTP = {
	generatedSecret: () => {
		const secret = process.env.SECRET_TFA
		return secret
	},
	generatedToken: (secret) => {
		return totp.generate(secret);
	},
	getTime: () => {
		return totp.timeUsed()
	},
	getTimeRemaining: () => {
		return totp.timeRemaining()
	},
	checkToken: (token, secret) => {
		return totp.check(token, secret)
	}
}
module.exports = TOTP
